- type: antag
  id: Heretic
  name: roles-antag-heretic-name
  antagonist: true
  setPreference: true
  objective: roles-antag-heretic-description
  requirements:
  - !type:DepartmentTimeRequirement
  department: Security
  time: 36000 # 10h
  - !type:DepartmentTimeRequirement
  department: Medical
  time: 36000 # 10h
  guides: [ Heretics ]

- type: startingGear
  id: HereticGear
  storage:
    back:
    - CodexCicatrix
    - OrganHumanHeart
